chirc:build:
    stage: build
    script:
      - make -C chirc/ clean chirc
    only: 
      - master
    artifacts:
      expire_in: 1 hour
      paths:
        - chirc/chirc

chirc:tests:
    stage: test
    script:
      - make -C chirc/ -k tests grade
    dependencies:
      - chirc:build
    artifacts:
      expire_in: 3 weeks
      when: always
      paths:
        - chirc/tests/report.json
    only:
      - master
